apiVersion: v1
kind: Service
metadata:
  labels:
    name: cassandra
  name: cassandra
spec:
  type: NodePort
  ports: 
    - port: 9042
      name: container-port
    - port: 7000
      name: storage-port
    - port: 7001
      name: ssl-storage-port
    - port: 9160
      name: rpc-port
  selector:
    name: cassandra
