apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cassandra
  template:
    metadata:
      labels:
        name: cassandra
    spec:
      containers:
      - args:
        - /bin/bash
        - -c
        - sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh
          cassandra -f
        image: cassandra:2.2
        name: cassandra
        ports:
        - containerPort: 9042
      restartPolicy: Always

