apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: edge
  template:
    metadata:
      labels:
        app: edge
    spec:
      containers:
      - name: edge
        image: edge:1.0
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
      restartPolicy: Always

