apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: feed
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: feed
    spec:
      containers:
      - image: feed3:1.0
        name: feed
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
