apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: feed
  name: feed
spec:
  type: NodePort
  ports:
  - name: "8088"
    port: 8088
    targetPort: 8080
  selector:
    io.kompose.service: feed
status:
  loadBalancer: {}
