apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: feed
  template:
    metadata:
      labels:
        app: feed
    spec:
      containers:
      - env:
        image: feed5:1.0
        name: feed
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
      restartPolicy: Always

