apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: feed
spec:
  replicas: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: feed
  template:
    metadata:
      labels:
        app: feed
    spec:
      containers:
      - name: feed
        env:
        - name: APPLICATION_SECRET
          value: LGG7q:ZHimG613xJXWL50cwgJ:nx6soU:XcPj2MhJ;GR[F0]ag:90cqpJ_
        envFrom:
        - configMapRef:
            name: feed-config
        image: feed12:1.0
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
      restartPolicy: Always

