apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: feed
  template:
    metadata:
      labels:
        app: feed
    spec:
      containers:
      - name: feed
        envFrom:
        - configMapRef:
            name: feed-config
        image: gengstrand/feed10:1.0
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
      restartPolicy: Always

