apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  type: NodePort
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  - name: "2181"
    port: 2181
    targetPort: 2181
  selector:
    io.kompose.service: kafka
status:
  loadBalancer: {}
