apiVersion: v1
kind: Service
metadata:
  name: kibana-logger
  createTimestamp: null
  labels:
    io.kompose.service: kibana-logger
  name: kibana-logger
spec:
  type: LoadBalancer
  ports:
  - port: 5601
    protocol: TCP
    targetPort: ui
  selector:
    io.kompose.service: kibana-logger
status:
  loadBalancer: {}
