apiVersion: v1
kind: Service
metadata:
  name: kibana-logger
  labels:
    name: kibana-logger
  name: kibana-logger
spec:
  type: LoadBalancer
  ports:
  - port: 5601
    protocol: TCP
    targetPort: ui
  selector:
    name: kibana-logger
