apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kong-proxy
        app: kong
    spec:
      containers:
      - name: kong
        image: kong:0.15.0
        env:
          - name: KONG_DATABASE
            value: cassandra
          - name: KONG_CASSANDRA_CONTACT_POINTS
            value: cassandra
          - name: KONG_CASSANDRA_KEYSPACE
            value: kong
          - name: KONG_CASSANDRA_REPL_FACTOR
            value: "2"
          - name: KONG_DB_UPDATE_PROPAGATION
            value: "2"
          - name: KONG_PROXY_ACCESS_LOG
            value: "/dev/stdout"
          - name: KONG_ADMIN_LISTEN
            value: "0.0.0.0:8001"
          - name: KONG_ADMIN_ACCESS_LOG
            value: "/dev/stdout"
          - name: KONG_PROXY_ERROR_LOG
            value: "/dev/stderr"
          - name: KONG_ADMIN_ERROR_LOG
            value: "/dev/stderr"      
        ports:
        - name: kong-admin
          containerPort: 8001
          protocol: TCP
        - name: knog-proxy
          containerPort: 8000
          protocol: TCP
        - name: kong-proxy-ssl
          containerPort: 8443
          protocol: TCP
        - name: kong-admin-ssl
          containerPort: 8444
          protocol: TCP
