apiVersion: v1
kind: Service
metadata:
  labels:
    name: kong-logger
  name: kong-logger
spec:
  type: NodePort
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
  selector:
    name: kong-logger
