apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kong-logger
  template:
    metadata:
      labels:
        name: kong-logger
    spec:
      containers:
      - env:
        image: gengstrand/kong-logger:1.0
        name: kong-logger
        ports:
        - containerPort: 8888
      restartPolicy: Always

