apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: react:1.0
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
      restartPolicy: Always

