{{- if .Values.useIngress -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: elastic-ingress
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: elasticsearch
          servicePort: 9200
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kibana-ingress
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: kibana-logger
          servicePort: 5601
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: grafana
          servicePort: 3000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: load-test-ingress
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: load-test
          servicePort: 8080
{{- end }}