{{- if .Values.gui -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: react
  name: react
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: react
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: gengstrand/react:1.0
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
      restartPolicy: Always
{{- end }}