name: analyze-source-code
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  count-file-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: report-results
        run: |
          import os
          if __name__ == '__main__':
              ftc = {}
              for root, dirs, files in os.walk("."):
                  for name in files:
                      np = name.split('.')
                      ft = np[-1]
                      if len(ft) <= 5:
                         if ft in ftc:
                            ftc[ft] = ftc[ft] + 1
                         else:
                            ftc[ft] = 1
              for k, v in ftc.items():
                  print(k, v)
        shell: python
